const state = {
  menuList: [
    { name: "All Dishes", selected: true, category: "all-dishes" },
    { name: "Hot Dishes", selected: false, category: "hot-dishes" },
    { name: "Cold Dishes", selected: false, category: "cold-dishes" },
    { name: "Soup", selected: false, category: "soup" },
    { name: "Grill", selected: false, category: "grill" },
    { name: "Appetizer", selected: false, category: "appetizer" },
    { name: "Dessert", selected: false, category: "dessert" },
  ],
  optionalMenu: [
    { name: "Delivery", orderDish: "delivery" },
    { name: "Dine in", orderDish: "dineIn" },
    { name: "To go", orderDish: "toGo" },
  ],
  foodList: [
    {
      id: 1,
      img: new URL("@/assets/images/dishes/dish-1.png", import.meta.url),
      title: "Spicy seasoned seafood noodles",
      price: 2.29,
      quantity: 5,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "hot-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: false,
      },
    },
    {
      id: 2,
      img: new URL("@/assets/images/dishes/dish-2.png", import.meta.url),
      title: "Salted Pasta with mushroom sauce",
      price: 2.69,
      quantity: 23,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "cold-dishes",
      isShown: true,
      orderDish: {
        delivery: false,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 3,
      img: new URL("@/assets/images/dishes/dish-3.png", import.meta.url),
      title: "Beef dumpling in hot and sour soup",
      price: 2.99,
      quantity: 11,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "grill",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: false,
      },
    },
    {
      id: 4,
      img: new URL("@/assets/images/dishes/dish-4.png", import.meta.url),
      title: "Healthy noodle with spinach leaf",
      price: 3.29,
      quantity: 24,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "appetizer",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 5,
      img: new URL("@/assets/images/dishes/dish-5.png", import.meta.url),
      title: "Hot spicy fried rice with omelet",
      price: 3.49,
      quantity: 19,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "hot-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: false,
        toGo: true,
      },
    },
    {
      id: 6,
      img: new URL("@/assets/images/dishes/dish-6.png", import.meta.url),
      title: "Duck Five Ways, Berlu",
      price: 4.59,
      quantity: 11,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "grill",
      isShown: true,
      orderDish: {
        delivery: false,
        dineIn: true,
        toGo: false,
      },
    },
  ],
  selectedDishesList: [],
};

const getters = {
  getMenuList: (state) => {
    return state.menuList;
  },
  getOptionalMenu: (state) => {
    return state.optionalMenu;
  },
  getFoodList: (state) => {
    return state.foodList;
  },
};

const mutations = {};

const actions = {};

export default {
  state,
  getters,
  mutations,
  actions,
};

/* foodList: [
    {
      id: 1,
      img: "dish-1.png",
      title: "Spicy seasoned seafood noodles",
      price: 2.29,
      quantity: 5,
      maxLimit: 5,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "hot-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: false,
      },
    },
    {
      id: 2,
      img: "dish-2.png",
      title: "Salted Pasta with mushroom sauce",
      price: 2.69,
      quantity: 23,
      maxLimit: 23,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "cold-dishes",
      isShown: true,
      orderDish: {
        delivery: false,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 3,
      img: "dish-3.png",
      title: "Beef dumpling in hot and sour soup",
      price: 2.99,
      quantity: 11,
      maxLimit: 11,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "grill",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: false,
      },
    },
    {
      id: 4,
      img: "dish-4.png",
      title: "Healthy noodle with spinach leaf",
      price: 3.29,
      quantity: 24,
      maxLimit: 24,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "appetizer",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 5,
      img: "dish-5.png",
      title: "Hot spicy fried rice with omelet",
      price: 3.49,
      quantity: 19,
      maxLimit: 19,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "hot-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: false,
        toGo: true,
      },
    },
    {
      id: 6,
      img: "dish-6.png",
      title: "Duck Five Ways, Berlu",
      price: 4.59,
      quantity: 11,
      maxLimit: 11,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "grill",
      isShown: true,
      orderDish: {
        delivery: false,
        dineIn: true,
        toGo: false,
      },
    },
  ], */
