const state = {
  menuList: [
    { name: "All Dishes", selected: true, category: "all-dishes" },
    { name: "Hot Dishes", selected: false, category: "hot-dishes" },
    { name: "Cold Dishes", selected: false, category: "cold-dishes" },
    { name: "Soup", selected: false, category: "soup" },
    { name: "Grill", selected: false, category: "grill" },
    { name: "Appetizer", selected: false, category: "appetizer" },
    { name: "Dessert", selected: false, category: "dessert" },
  ],
  optionalMenu: [
    { name: "Delivery", orderDish: "delivery" },
    { name: "Dine in", orderDish: "dineIn" },
    { name: "To go", orderDish: "toGo" },
  ],
  foodList: [
    {
      id: 1,
      img: new URL("@/assets/images/dishes/dish-1.png", import.meta.url),
      title: "Spicy seasoned seafood noodles",
      price: 2.29,
      quantity: 5,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "hot-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: false,
      },
    },
    {
      id: 2,
      img: new URL("@/assets/images/dishes/dish-2.png", import.meta.url),
      title: "Salted Pasta with mushroom sauce",
      price: 2.69,
      quantity: 23,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "cold-dishes",
      isShown: true,
      orderDish: {
        delivery: false,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 3,
      img: new URL("@/assets/images/dishes/dish-3.png", import.meta.url),
      title: "Beef dumpling in hot and sour soup",
      price: 2.99,
      quantity: 11,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "grill",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: false,
      },
    },
    {
      id: 4,
      img: new URL("@/assets/images/dishes/dish-4.png", import.meta.url),
      title: "Healthy noodle with spinach leaf",
      price: 3.29,
      quantity: 24,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "appetizer",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 5,
      img: new URL("@/assets/images/dishes/dish-5.png", import.meta.url),
      title: "Hot spicy fried rice with omelet",
      price: 3.49,
      quantity: 19,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "hot-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: false,
        toGo: true,
      },
    },
    {
      id: 6,
      img: new URL("@/assets/images/dishes/dish-6.png", import.meta.url),
      title: "Duck Five Ways, Berlu",
      price: 4.59,
      quantity: 11,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "grill",
      isShown: true,
      orderDish: {
        delivery: false,
        dineIn: true,
        toGo: false,
      },
    },
    {
      id: 7,
      img: new URL("@/assets/images/dishes/dish-7.png", import.meta.url),
      title: "Lingonberry Almond Cake, Lost Larson",
      price: 1.29,
      quantity: 25,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "soup",
      isShown: true,
      orderDish: {
        delivery: false,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 8,
      img: new URL("@/assets/images/dishes/dish-8.png", import.meta.url),
      title: "Arancini, Vespertine",
      price: 3.49,
      quantity: 14,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "hot-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 9,
      img: new URL("@/assets/images/dishes/dish-9.png", import.meta.url),
      title: "Blue Crab Meatballs and Spaghetti, Maialino Mare",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "dessert",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 10,
      img: new URL("@/assets/images/dishes/dish-10.png", import.meta.url),
      title: "Brisket Tostadas, Loro",
      price: 2.29,
      quantity: 29,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "cold-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: false,
        toGo: false,
      },
    },
    {
      id: 11,
      img: new URL("@/assets/images/dishes/dish-11.png", import.meta.url),
      title: "Grilled Chicken, Laser Wolf",
      price: 2.69,
      quantity: 11,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "grill",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: false,
        toGo: true,
      },
    },
    {
      id: 12,
      img: new URL("@/assets/images/dishes/dish-12.png", import.meta.url),
      title: "Gluten Free Chocolate Cake, Jinju Patisserie",
      price: 2.99,
      quantity: 16,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "grill",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 13,
      img: new URL("@/assets/images/dishes/dish-13.png", import.meta.url),
      title: "The Original Butcher’s Feast, Cote",
      price: 3.29,
      quantity: 22,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "appetizer",
      isShown: true,
      orderDish: {
        delivery: false,
        dineIn: false,
        toGo: true,
      },
    },
    {
      id: 14,
      img: new URL("@/assets/images/dishes/dish-14.png", import.meta.url),
      title: "Grilled Dorade, Vernick Fish",
      price: 3.49,
      quantity: 13,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "appetizer",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: false,
      },
    },
    {
      id: 15,
      img: new URL("@/assets/images/dishes/dish-15.png", import.meta.url),
      title: "Everything They Serve, Hestia",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "soup",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 16,
      img: new URL("@/assets/images/dishes/dish-16.png", import.meta.url),
      title: "Lamb Curry, Eem",
      price: 3.29,
      quantity: 22,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "soup",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: false,
        toGo: false,
      },
    },
    {
      id: 17,
      img: new URL("@/assets/images/dishes/dish-17.png", import.meta.url),
      title: "Lobster Bao, Essex Pearl",
      price: 3.49,
      quantity: 13,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "appetizer",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: false,
      },
    },
    {
      id: 18,
      img: new URL("@/assets/images/dishes/dish-18.png", import.meta.url),
      title: "Manti Dumplings, Albi",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "appetizer",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: false,
        toGo: true,
      },
    },
    {
      id: 19,
      img: new URL("@/assets/images/dishes/dish-19.png", import.meta.url),
      title: "Lobster Bolognese with Truffle Sauce, Melisse",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "dessert",
      isShown: true,
      orderDish: {
        delivery: false,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 20,
      img: new URL("@/assets/images/dishes/dish-20.png", import.meta.url),
      title: "Mentaiko Carbonara, Kaisho at Yugen",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "dessert",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 21,
      img: new URL("@/assets/images/dishes/dish-21.png", import.meta.url),
      title: "Kaiseki Jubako, n/naka",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "dessert",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: false,
      },
    },
    {
      id: 22,
      img: new URL("@/assets/images/dishes/dish-22.png", import.meta.url),
      title: "Pan Roasted Brioche, Auburn",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "soup",
      isShown: true,
      orderDish: {
        delivery: false,
        dineIn: false,
        toGo: true,
      },
    },
    {
      id: 23,
      img: new URL("@/assets/images/dishes/dish-23.png", import.meta.url),
      title: "Sweet Potato and Pecan Taco, Nixta",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "soup",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: false,
        toGo: true,
      },
    },
    {
      id: 24,
      img: new URL("@/assets/images/dishes/dish-24.png", import.meta.url),
      title: "Pheasant, Wherewithall",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "hot-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 25,
      img: new URL("@/assets/images/dishes/dish-25.png", import.meta.url),
      title: "Pike Quenelle, Grand Café",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "hot-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: false,
        toGo: false,
      },
    },
    {
      id: 26,
      img: new URL("@/assets/images/dishes/dish-26.png", import.meta.url),
      title: "Rice Krispies Treats, Demi",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "hot-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: true,
        toGo: true,
      },
    },
    {
      id: 27,
      img: new URL("@/assets/images/dishes/dish-27.png", import.meta.url),
      title: "Spicy Sea Bass Temaki, Nami Nori",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "cold-dishes",
      isShown: true,
      orderDish: {
        delivery: false,
        dineIn: true,
        toGo: false,
      },
    },
    {
      id: 28,
      img: new URL("@/assets/images/dishes/dish-28.png", import.meta.url),
      title: "Sunchoke Flatbread, Rustic Canyon",
      price: 3.59,
      quantity: 18,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "cold-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: false,
        toGo: false,
      },
    },
    {
      id: 29,
      img: new URL("@/assets/images/dishes/dish-29.png", import.meta.url),
      title: "Pork Trotter Tonkotsu, Emilie’s",
      price: 3.59,
      quantity: 17,
      counter: 1,
      discount: 0,
      sum: null,
      comment: "",
      desc: "Bowls available",
      category: "cold-dishes",
      isShown: true,
      orderDish: {
        delivery: true,
        dineIn: false,
        toGo: true,
      },
    },
  ],
};

const getters = {
  getMenuList: (state) => {
    return state.menuList;
  },
  getOptionalMenu: (state) => {
    return state.optionalMenu;
  },
  getFoodList: (state) => {
    return state.foodList;
  },
};

const mutations = {};

const actions = {};

export default {
  state,
  getters,
  mutations,
  actions,
};